help = {}
help.longdesc = {
	["default:apple"] = "Eat it to restore 2 HP.",
	["default:furnace"] = "Cooks several items, using a furnace fuel, into something else.",
	["default:chest"] = "Provides 32 slots of inventory space.",
	["default:chest_locked"] = "Provides 32 slots of inventory space, is accessible only to the player who placed it.",
	["default:chest_locked"] = "Provides 32 slots of inventory space, is accessible only to the player who placed it.",
	["default:stone"] = "A very common block in the world of Minetest. It sometimes contains ores. Usable for a variety in crafting recipes. Can be dug with a wooden pickaxe or better.",
	["default:desert_stone"] = "A less common block in the world, usually only found in deserts. Can be dug with a wooden pickaxe or better.",
	["default:stone_with_coal"] = "Some natural coal! Can be dug with a wooden pickaxe or better.",
	["default:stone_with_iron"] = "Some natural iron! Can be dug with a stone pickaxe or better.",
	["default:stone_with_copper"] = "Some natural copper! Can be dug with a stone pickaxe or better.",
	["default:stone_with_mese"] = "This stone contains a small amount of Mese! Can be dug with a steel pickaxe or better to obtain a mese crystal.",
	["default:stone_with_gold"] = "Some natural gold! Can be dug with a steel pickaxe or better.",
	["default:stone_with_diamond"] = "Hooray, diamonds! Can be dug with a steel pickaxe or better.",
	["default:stonebrick"] = "A decorational block.",
	["default:desert_stonebrick"] = "A decorational block.",
	["default:dirt_with_grass"] = "Natural soil for a variety of plants. It has been exposed to sunlight and is thus grassy. Can be dug with a shovel.",
	["default:dirt"] = "Natural soil for a variety of plants. Its top will become grassy if it becomes exposed to sunlight. Can be dug with a shovel.",
	["default:sand"] = "An unstable block, it will fall if nothing is below it. Usually found at beaches. It is best dug with a shovel.",
	["default:desert_sand"] = "An unstable block, it will fall if nothing is below it. Usually found in deserts. It is best dug with a shovel.",
	["default:gravel"] = "An unstable block, it will fall if nothing is below it. It is best dug with a shovel.",
	["default:sandstone"] = "A decorational block. It can be mined with a pickaxe or shovel",
	["default:sandstonebrick"] = "A decorational block.",
	["default:clay"] = "Clay.",
	["default:brick"] = "A decorational block.",
	["default:tree"] = "A trunk of an ordinary tree. You can break it with your bare hands!",
	["default:jungletree"] = "A trunk of a jungle tree. You can break it with your bare hands!",
	["default:wood"] = "A decorational and flammable block.",
	["default:junglewood"] = "A decorational and flammable block.",
	["default:pinewood"] = "A decorational and flammable block.",
	["default:sapling"] = "When placed on dirt and exposed to sunlight, this sapling will grow into an ordinary tree or an apple tree after some time.",
	["default:junglesapling"] = "When placed on dirt and exposed to sunlight, this sapling will grow into a large jungle tree after some time.",
	["default:pine_sapling"] = "When placed on dirt and exposed to sunlight, this sapling will grow into a pine tree after some time.",
	["default:leaves"] = "Leaves of an ordinary tree or apple tree. It will decay if there is no tree trunk near it, unless you have placed the leaves manually.",
	["default:jungleleaves"] = "Leaves of a jungle tree. It will decay if there is no tree trunk near it, unless you have placed the leaves manually.",
	["default:pine_needles"] = "Needles of a pine tree. It will decay if there is no tree trunk near it, unless you have placed the pine needles manually.",
	["default:cactus"] = "A piece of cactus usually found in deserts. Cactus placed on desert sand will slowly grow up to 4 cactus blocks high.",
	["default:papyrus"] = "A papyrus piece usually found near water. Papyrus will grow up to 4 blocks high when it is near a water source.",
	["default:bookshelf"] = "A bookshelf provides space for 16 books.",
	["default:glass"] = "A decorational, transparent block.",
	["default:fence_wood"] = "A fence post. When multiple of these are placed to next to each other, they will automatically build a nice fence structure. You can easily jump over a low fence.",
	["default:rail"] = "Railroad tracks. Place these on the ground to build your railway, the blocks will automatically connect to each other nicely.",
	["default:ladder"] = "A piece of ladder which allows you to move vertically.",
	["default:water_flowing"] = "You can swim easily in water, but you need to catch your breath from time to time.",
	["default:water_source"] = "You can swim easily in water, but you need to catch your breath from time to time.",
	["default:lava_source"] = "Don't touch the lava, it will hurt you very much and once you're in, it is hard to get out.",
	["default:lava_flowing"] = "Don't touch the lava, it will hurt you very much and once you're in, it is hard to get out.",
	["default:torch"] = "Provides plenty of light, but not as much as a sun would do. It can be placed on almost any block facing any direction.",
	["default:sign_wall"] = "A sign which is placed at walls. You can write anything you want on it.",

	["default:cobble"] = "A decorational block.",
	["default:desert_cobble"] = "A decorational block.",
	["default:mossycobble"] = "A decorational block.",
	["default:coalblock"] = "A decorational block.",
	["default:steelblock"] = "A decorational block.",
	["default:copperblock"] = "A decorational block.",
	["default:bronzeblock"] = "A decorational block.",
	["default:goldblock"] = "A decorational block.",
	["default:diamondblock"] = "A very hard decorational block.",
	["default:obsidian_glass"] = "A decorational, transparent block.",
	["default:obsidian"] = "A hard mineral which is generated when a lava source meets a water source.",
	["default:nyancat"] = "A pop-tart cat in a block. Just for fun.",
	["default:nyancat_rainbow"] = "A rainbow in a block. Just for fun.",
	["default:grass_1"] = "Some grass. On a dirt with grass block, it will slowly spread.",


	["bones:bones"] = "These are the remains of a deceased player. It contains the player's inventory.",

	["farming:soil"] = "Dry soil, this is where you can grow crops on. Dry soil will become wet if a water source is near.",
	["farming:soil_wet"] = "Wet soil, this is where you can grow crops on.",
	["farming:desert_sand_soil"] = "Dry soil, this is where you can grow crops on. Dry soil will become wet if a water source is near.",
	["farming:desert_sand_soil_wet"] = "Wet soil, this is where you can grow crops on.",

	["tnt:tnt"] = "An explosive device which is capable of damaging living beings and destroys blocks around it, shortly after it has been ignited. With a small chance, blocks may drop as an item. TNT can be ignited by explosions and fire.",
	["tnt:gunpowder"] = "Gunpowder is used to craft TNT and to create gunpowder trails which can be ignited.",

	["fire:basic_flame"] = "Fire is a damaging and destructive but short-lived kind of block. It will destroy and spread towards near flammable blocks, but fire will disappear if there is nothing to burn left. Fire will be extinguished faster if water is near it (no matter from which direction). A single fire block can be destroyed safely by punching it, but it is hurtful if you stand directly in fire.",

	["bedrock2:bedrock"] = "If you have found this block then you have reached the bottom of the world. Bedrock cannot be moved, altered or destroyed by any means.",

	["doors:trapdoor"] = "A trapdoor covers a hole in the floor and can be opened manually to access the area below it. An opened trapdoor can be climbed like a ladder.",
}

help.usagehelp = {
	["default:apple"] = "Leftclick to eat.",
	["default:furnace"] = "Rightclick the furnace to view it. Place a furnace fuel in the lower slot and the source material in the upper slot. The furnace will slowly use its fuel to smelt the item. The result will be placed into the 4 slots at the right side.",
	["default:chest"] = "Rightclick the chest to open it and to exchange items.",
	["default:chest_locked"] = "Rightclick the chest to open it and to exchange items. This is only possible if you own the chest.",
	["default:ladder"] = "Hold the jump key to climb up and the sneak or use key (depends on configuration) to climb down.",
	["default:sign_wall"] = "Rightclick the sign to edit the text.",

	["default:bookshelf"] = "Rightclick to open the bookshelf. You can store one book per inventory slot. To collect the bookshelf, you must make sure it does not contain any books.",

	["bones:bones"] = "Rightclick to access the inventory, dig it to obtain all items immediately. If these are not your bones, you have to wait 10 minutes before you can do this. It is only possible to take from this inventory, nothing can be stored into it.",

	["tnt:gunpowder"] = "Place gunpowder on the ground to create gunpowder trails. Punch it with a torch to light the gunpowder, which will then ignore neighbor gunpowder and TNT.",
	["tnt:tnt"] = "Place the TNT on the ground and punch it with a torch to light it and quickly get in a safe distance before it explodes. A burning gunpowder trail will also light the TNT.",

	["doors:trapdoor"] = "Rightclick the trapdoor to open or close it. When the trapdoor is open, use the sneak or use key (depends on your configuration) to climb down, and the jump key to climb up.",
}
